name: build

on: [push, pull_request]

env:
  FORCE_COLOR: 3

jobs:
  test:
    if: github.event_name == 'pull_request' || github.ref == 'refs/heads/main'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - php: '7.4'
            os: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.15.3' # renovate:keep-up-to-date
      - name: Install npm dependencies
        run: npm ci
      - name: Prettier
        run: npm run prettier-check
      - name: Lint
        run: npm run tslint
      - name: Build VS Code extension
        run: npm run build
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer
      - name: Composer Install
        run: composer install --prefer-dist --no-interaction --optimize-autoloader
#  release:
#    runs-on: ubuntu-18.04
#    needs: test
#    if: github.repository_owner == 'zobo' && github.event_name == 'push' && github.ref == 'refs/heads/main'
#    steps:
#      - uses: actions/checkout@v2
#      - name: Setup Node.js
#        uses: actions/setup-node@v2
#        with:
#          node-version: '14.15.3' # renovate:keep-up-to-date
#      - name: Install npm dependencies
#        run: npm ci
#      - name: Build VS Code extension
#        run: npm run build
#      - name: Setup PHP
#        uses: shivammathur/setup-php@v2
#        with:
#          php-version: 7.4
#          tools: composer
#      - name: Composer Install
#        run: composer install --prefer-dist --no-interaction --optimize-autoloader
#      - name: Release
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
#        run: npm run semantic-release
